openapi: 3.0.1
info:
  title: Hellow world Plugin
  description:  Plugins for saying Hello
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /todos/{username}:
    get:
      operationId: getHelloWorld
      summary: Get a response to say hello world.
      parameters:
      - in: path
        name: name
        schema:
            type: string
        required: true
        description: The name of the user.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getHelloWorldResponse'
    
components:
  schemas:
   getHelloWorldResponse:
      type: object
      properties:
        hello:
          type: string
      
            type: string
          description: The hello world
    